#include "mapreduce.h"

int main(int argc, char *argv[]) {
	
	if(argc < 4) {
		printf("Less number of arguments.\n");
		printf("./mapreduce #mappers #reducers inputFile\n");
		exit(0);
	}

	// ###### DO NOT REMOVE ######
	int nMappers 	= strtol(argv[1], NULL, 10);
	int nReducers 	= strtol(argv[2], NULL, 10);
	char *inputFile = argv[3];
	int stat1;
	int stat2;

	// ###### DO NOT REMOVE ######
	bookeepingCode();

	// ###### DO NOT REMOVE ######
	pid_t pid = fork();
	if(pid == 0){
		//send chunks of data to the mappers in RR fashion
		sendChunkData(inputFile, nMappers);
		exit(0);
	}
	sleep(1);


	// To do
	// spawn mappers processes and run 'mapper' executable using exec

	// Creates amount of mapper processes as specified and calls mapper executable with each child process
	pid_t map_pid[nMappers];
	for (int i = 0; i < nMappers; i++) {

		if (map_pid[i] = fork() == 0) {
			char* arr[] = {"./mapper", "mapper", "1", NULL};
			execvp(*arr, arr);
			exit(0);
		}
		else if (map_pid[i] < 0) {
			printf("Error with exec in mapper");
		}
	}
	
	// To do
	// wait for all children to complete execution
	for (int i = 0; i < nMappers; i++) {
		waitpid(map_pid[i], &stat1, 0);
	}

	// ###### DO NOT REMOVE ######
    // shuffle sends the word.txt files generated by mapper 
    // to reducer based on a hash function

	pid = fork();
	if(pid == 0) {
		shuffle(nMappers, nReducers);
		exit(0);
	}
	sleep(1);


	// To do
	// spawn reducer processes and run 'reducer' executable using exec

	// Creates amount of reducer processes as specified and calls reducer executable with each child process
	pid_t red_pid[nReducers];
	for (int i = 0; i < nReducers; i++) {
		if (red_pid[i] = fork() == 0) {
			char* arr2[] = {"./reducer", "reducer", "1", NULL};
			execvp(*arr2, arr2);
			exit(0);
		}
		else if (red_pid[i] < 0) {
			printf("Error with exec in reducer");
		}
	}

	// To do
	// wait for all children to complete execution
	for (int i = 0; i < nMappers; i++) {
		waitpid(red_pid[i], &stat2, 0);
	}

	return 0;
}
